scrape_configs:
  - job_name: "docker"
    scrape_interval: "1s"
    static_configs:
      - targets: ["host.docker.internal:9323"]
  - job_name: "cadvisor"
    scrape_interval: "1s"
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: "nodeExporter"
    scrape_interval: "1s"
    static_configs:
      - targets: ["nodeExporter:9100"]
  - job_name: "comedyhub"
    scrape_interval: "1s"
    static_configs:
      - targets: ["api-web:3005"]
    metrics_path: /api/metrics